# Generated by Django 4.2 on 2023-04-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnail/images')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('demo', models.CharField(blank=True, max_length=200, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Views')),
                ('likes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
