# Generated by Django 4.2 on 2023-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, null=True, verbose_name='Live Demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Repo'),
        ),
    ]
