# Generated by Django 4.2 on 2023-04-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_demo_alter_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(max_length=300, verbose_name='Languages Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/images', verbose_name='Project Image'),
        ),
    ]
